services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - app
 
  backend:
    build: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    
    depends_on:
      - qdrant
    
    # command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
 
    env_file:
      - .env
    restart: always
    networks:
      - app
    container_name: backend
 
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
      - qdrant
    volumes:
      - ./frontend:/app
 
    # command: poetry run streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
 
    restart: always
    networks:
      - app
    container_name: frontend
    

 
networks:
  app:
    driver: bridge
 
configs:
  qdrant_config:
    content: |
      log_level: INFO      